### PR TITLE
Fixed Lua table-in-table processing

### LINKED ISSUE #774: [BUG - Lua] Converting multi-dimensional tables (i.e. FTransform) into function params of type StructProperty is broken
**Branch or Release**
3ce18c0d26a73570918091a08ebfb2643895c926

**Game and Engine Version**
N/A

**Describe the bug**
You get this kind of error when trying to pass a table with other tables in it to a function param:
```
[push_objectproperty] Error:
 Value must be UObject or nil
    Operation: Set
    Base: 0x5321ef40
    Data: 0x5321ef88
    Property (0x3580f980): ObjectProperty /Script/Engine.GameplayStatics:BeginDeferredActorSpawnFromClass:Owner
    StoredAtIndex: 1
    CreateNewIfGetNonTrivialLocal: true


LUA Stack dump -> START------------------------------

1	table	0x5ac1d5c0

LUA Stack dump -> END----------------------------
```

**To Reproduce**
Make a mod with the following code:
```lua
local UEHelpers = require("UEHelpers")

-- Only setting Transform.Translation because that's all that's needed for this bug.
-- The bug appears even if you fully construct all FTransform fields.
local Transform = {}
Transform.Translation = {}
local World = UEHelpers.GetWorld()
local Class = World:GetClass() -- Ignore how ridiculous this is, it's not relevant.
local GamePlayStatics = UEHelpers.GetGameplayStatics()
local Actor = GamePlayStatics:BeginDeferredActorSpawnFromClass(World, Class, Transform, 1, nil)
```

**Expected behavior**
No Lua error should occur, and the game function should be executed.

### PR DESCRIPTION
**Pull request by UE4SS**
Fixes #774

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

See the code example in #774

**Checklist**

- [x] I have added the necessary description of this PR to the changelog, and I have followed the same format as other entries.

### CODE REVIEW

**Comment by igromanru** [comment]
Doesn't work for me.  
Here is an easy way to test:
```lua
local transform = {
	Rotation = {
		X = 1.0,
		Y = 2.0,
		Z = 3.0,
		W = 4.0
	},
	Translation = {
		X = 11.0,
		Y = 22.0,
		Z = 33.0
	},
	Scale3D = {
		X = 21.0,
		Y = 32.0,
		Z = 43.0
	}
}
local transformString = UEHelpers.GetKismetStringLibrary():Conv_TransformToString(transform)
print("transformString: " .. transformString:ToString() .. "\n")
```

**Comment by CookiePLMonster** [comment]
Regresses my test case with nested FStructs:

```lua
RegisterBeginPlayPostHook(function(ActorParam)
    local Actor = ActorParam:get()
    if Actor:GetAddress() ~= CachedCourseSkyActor:GetAddress() then
		return
	end

	SavedUDSState = {}
	Actor['Create UDS and UDW State for Saving'](SavedUDSState)
	print('Before restore: ' .. Actor['Time Of Day'] .. '\n')
	Actor['Apply Saved UDS and UDW State'](SavedUDSState)
	print('After restore: ' .. Actor['Time Of Day'] .. '\n')
end)
```

Without this PR, the behaviour of restoring is incorrect, but it doesn't crash:
```
[2025-02-03 16:34:46.9746305] [Lua] Before restore: 353.36666666667
[2025-02-03 16:34:46.9751539] [Lua] After restore: 2300.0666666667
```

With this PR, I get
```
[2025-02-03 16:45:27.6848804] [Lua] Before restore: 353.36666666667
[2025-02-03 16:45:27.6851374] Error: [push_objectproperty] Error:
 Value must be UObject or nil
    Operation: Set
    Base: 0x5f5117dbc0
    Data: 0x5f5117dca8
    Property (0x17fc3633580): ObjectProperty /Game/UltraDynamicSky/Blueprints/System/UDS_and_UDW_State.UDS_and_UDW_State:Weather_159_65D3DE2946AD276E7F18E484BA19512B
    StoredAtIndex: -1
    CreateNewIfGetNonTrivialLocal: true
```

**Comment by UE4SS** [comment]
Test again please, I made a change.

File: UE4SS/src/LuaType/LuaUObject.cpp [hunk 1]
```diff
@@ -579,7 +579,6 @@ namespace RC::LuaType
             // At the bottom of the stack now: table that has struct data
 
             // Duplicating the table and putting the duplicate at the top of the stack
```
Comment (UE4SS) [inline UE4SS/src/LuaType/LuaUObject.cpp:581]: Note: Delete this comment before merging, it's outdated!

**Comment by igromanru** [comment]
My test case works now.
```lua
local transform = GetKismetMathLibrary():MakeTransform(FVector(12.0, 13.0, 14.0), FRotator(22.0, 33.0, 44.0), FVector(1.0, 1.0, 1.0))
LogDebug("transform:", TableToString(transform))
local transformString = UEHelpers.GetKismetStringLibrary():Conv_TransformToString(transform)
print("transformString: " .. transformString:ToString() .. "\n")
```
The code is based on my [UE4SS BaseUtils](https://github.com/igromanru/BaseUtils-UE4SS).
Result:
```
transform: Translation: 
 X: 12.0
 Y: 13.0
 Z: 14.0
Rotation: 
 W: 0.89296963990073
 X: -0.30233446241743
 Y: -0.27406887532903
 Z: 0.18996143457609
Scale3D: 
 X: 1.0
 Y: 1.0
 Z: 1.0
transformString: Translation: X=12.000 Y=13.000 Z=14.000 Rotation: P=22.000000 Y=33.000000 R=44.000000 Scale: X=1.000 Y=1.000 Z=1.000
```

**Comment by CookiePLMonster** [comment]
Mine now works _partially_. The saved state of weather, cloud coverage, location etc. restores correctly, while time and date does not. Seems like those fields might not be handled correctly still:
```
---@field CurrentTime_212_A8A3081E448DDADDE3E0AE9D48603236 FDateTime
---@field StartingDate_213_8B4AC69C4C757F9C8F3B599C85B79B12 FDateTime
```

**Comment by UE4SS** [comment]
> Mine now works _partially_. The saved state of weather, cloud coverage, location etc. restores correctly, while time and date does not. Seems like those fields might not be handled correctly still:
> 
> ```
> ---@field CurrentTime_212_A8A3081E448DDADDE3E0AE9D48603236 FDateTime
> ---@field StartingDate_213_8B4AC69C4C757F9C8F3B599C85B79B12 FDateTime
> ```

The `FDateTime` struct doesn't have any reflected fields, that's why.
But an improvement here (though out of scope for this PR) would be to check if structs with unreflected members still have an accurate size in the UStruct/UScriptStruct, because if they do, we can possibly copy the raw bytes so that at least input/output operations will work better.
